@Organite.Api_HostAddress = https://localhost:7160

GET {{Organite.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Organite.Api_HostAddress}}/api/notes

###
GET {{Organite.Api_HostAddress}}/api/notes/123